#Numerical Computing with Python

Bibek Karki

2431483

In [1]:
import numpy as np
import time
import random
import warnings
warnings.filterwarnings('ignore')

print('NumPy version:', np.__version__)

NumPy version: 2.0.2


# Basic Vector and Matrix Operations with NumPy

Problem 1

Array Creation

Demonstrate six fundamental NumPy array initialisation methods.


In [2]:
#Task 1: Empty array (2×2)
empty_arr = np.empty((2, 2))
print('Task 1 — Empty array (2×2):')
print(empty_arr)
print('Note: np.empty() allocates memory without initialising values.')

Task 1 — Empty array (2×2):
[[3.64759993e-315 0.00000000e+000]
 [4.94065646e-324 6.54224304e-310]]
Note: np.empty() allocates memory without initialising values.


In [3]:
#Task 2: All-ones array (4×2)
ones_arr = np.ones((4, 2))
print('Task 2 — All-ones array (4×2):')
print(ones_arr)

Task 2 — All-ones array (4×2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
# Task 3: np.full — fill with a given value
full_arr = np.full((3, 3), fill_value=7)
print('Task 3 — np.full (3×3), fill_value=7:')
print(full_arr)

Task 3 — np.full (3×3), fill_value=7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [5]:
#  Task 4: np.zeros_like
reference_arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(reference_arr)
print('Reference array:', reference_arr.shape, reference_arr.dtype)
print('Task 4 — np.zeros_like:')
print(zeros_like_arr)

Reference array: (2, 3) int64
Task 4 — np.zeros_like:
[[0 0 0]
 [0 0 0]]


In [6]:
#  Task 5: np.ones_like
ones_like_arr = np.ones_like(reference_arr)
print('Task 5 — np.ones_like (same shape & dtype as reference_arr):')
print(ones_like_arr)

Task 5 — np.ones_like (same shape & dtype as reference_arr):
[[1 1 1]
 [1 1 1]]


In [8]:
#Task 6: List → NumPy array
new_list = [1, 2, 3, 4]
np_arr = np.array(new_list)
print('Original Python list :', new_list,  type(new_list))
print('Converted NumPy array:', np_arr,    type(np_arr))

Original Python list : [1, 2, 3, 4] <class 'list'>
Converted NumPy array: [1 2 3 4] <class 'numpy.ndarray'>


Problem 2

Array Manipulation: Numerical Ranges & Indexing

Range creation, reshaping, identity matrices, statistical aggregation, and structured array patterns


In [9]:
# Task 1: arange 10 to 49
range_arr = np.arange(10, 50)
print('Task 1 — np.arange(10, 50):')
print(range_arr)

Task 1 — np.arange(10, 50):
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
#Task 2: 3×3 matrix (0 to 8) using reshape
matrix_0_8 = np.arange(9).reshape(3, 3)
print('Task 2 — 3×3 matrix, values 0–8:')
print(matrix_0_8)

Task 2 — 3×3 matrix, values 0–8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
# Task 3: 3×3 identity matrix
identity = np.eye(3)
print('Task 3 — 3×3 Identity matrix:')
print(identity)

Task 3 — 3×3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# Task 4: Random array (size 30), find mean
np.random.seed(42)          # Seed for reproducibility
random_30 = np.random.random(30)
print('Task 4 — Random array (size 30):')
print(random_30)
print(f'\nMean: {random_30.mean():.6f}')

Task 4 — Random array (size 30):
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]

Mean: 0.438597


In [13]:
# Task 5: 10×10 random array — min and max
random_10x10 = np.random.random((10, 10))
print('Task 5 — 10×10 random array (first 3 rows shown):')
print(np.round(random_10x10[:3], 4))
print(f'\nMinimum: {random_10x10.min():.6f}')
print(f'Maximum: {random_10x10.max():.6f}')

Task 5 — 10×10 random array (first 3 rows shown):
[[0.6075 0.1705 0.0651 0.9489 0.9656 0.8084 0.3046 0.0977 0.6842 0.4402]
 [0.122  0.4952 0.0344 0.9093 0.2588 0.6625 0.3117 0.5201 0.5467 0.1849]
 [0.9696 0.7751 0.9395 0.8948 0.5979 0.9219 0.0885 0.196  0.0452 0.3253]]

Minimum: 0.005522
Maximum: 0.986887


In [14]:
#  Task 6: Zero array, replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1     # index 4 = 5th element
print('Task 6 — Zero array with 5th element = 1:')
print(zero_arr)

Task 6 — Zero array with 5th element = 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
# Task 7: Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print('Task 7 — Original :', arr)
print('         Reversed :', reversed_arr)

Task 7 — Original : [1 2 0 0 4 0]
         Reversed : [0 4 0 0 2 1]


In [16]:
#Task 8: 2D array with 1 on border, 0 inside
border_arr = np.ones((6, 6))
border_arr[1:-1, 1:-1] = 0
print('Task 8 — Border array (6×6):')
print(border_arr.astype(int))

Task 8 — Border array (6×6):
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [17]:
# Task 9: 8×8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1   # odd rows, even cols
checkerboard[::2, 1::2] = 1   # even rows, odd cols
print('Task 9 — 8×8 Checkerboard:')
print(checkerboard)

Task 9 — 8×8 Checkerboard:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3
Array Operations

  <p style="color: #444; margin: 0; font-family: Arial; font-size: 14px;">
    Given: &nbsp;<code>x = [[1,2],[3,5]]</code>, &nbsp;<code>y = [[5,6],[7,8]]</code>, &nbsp;<code>v = [9,10]</code>, &nbsp;<code>w = [11,12]</code>
  </p>
</div>

In [19]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
print('x =', x)
print('y =', y)
print('v =', v)
print('w =', w)

x = [[1 2]
 [3 5]]
y = [[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]


In [20]:
# Task 1 & 2: Addition and Subtraction
print('Task 1 — x + y:')
print(x + y)

print('\nTask 2 — x - y:')
print(x - y)

Task 1 — x + y:
[[ 6  8]
 [10 13]]

Task 2 — x - y:
[[-4 -4]
 [-4 -3]]


In [21]:
# Task 3 & 4: Scalar Multiplication and Squaring
print('Task 3 — x * 3:')
print(x * 3)

print('\nTask 4 — x squared (element-wise):')
print(x ** 2)
print('\ny squared (element-wise):')
print(y ** 2)

Task 3 — x * 3:
[[ 3  6]
 [ 9 15]]

Task 4 — x squared (element-wise):
[[ 1  4]
 [ 9 25]]

y squared (element-wise):
[[25 36]
 [49 64]]


In [22]:
#  Task 5: Dot Products
print('Task 5a — Dot product of v and w:')
print(np.dot(v, w))   # scalar

print('\nTask 5b — Dot product of x and v:')
print(np.dot(x, v))   # vector

print('\nTask 5c — Dot product of x and y:')
print(np.dot(x, y))   # matrix

Task 5a — Dot product of v and w:
219

Task 5b — Dot product of x and v:
[29 77]

Task 5c — Dot product of x and y:
[[19 22]
 [50 58]]


In [23]:
#Task 6: Concatenation
print('Task 6a — Concatenate x and y along rows (axis=0):')
print(np.concatenate((x, y), axis=0))

print('\nTask 6b — Concatenate v and w along column (vstack):')
print(np.vstack((v, w)))

Task 6a — Concatenate x and y along rows (axis=0):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Task 6b — Concatenate v and w along column (vstack):
[[ 9 10]
 [11 12]]


In [24]:
# Task 7: Concatenate x and v — Expected Error
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print('ValueError caught:', e)

ValueError caught: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem 4

Matrix Operations
  <p style="color: #444; margin: 0; font-family: Arial; font-size: 14px;">
    Given: &nbsp;<code>A = [[3,4],[7,8]]</code> &nbsp;and&nbsp; <code>B = [[5,3],[2,1]]</code>
  </p>
</div>

In [25]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
print('A =\n', A)
print('B =\n', B)

A =
 [[3 4]
 [7 8]]
B =
 [[5 3]
 [2 1]]


In [26]:
#  Proof 1: A × A⁻¹ = I
A_inv = np.linalg.inv(A)
product = np.round(np.dot(A, A_inv)).astype(int)
print('A⁻¹ =\n', A_inv.round(4))
print('\nA × A⁻¹ =\n', product)
print('\n Equals Identity matrix I')

A⁻¹ =
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A × A⁻¹ =
 [[1 0]
 [0 1]]

 Equals Identity matrix I


In [27]:
# Proof 2: AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print('AB =\n', AB)
print('\nBA =\n', BA)
print('\nAB == BA?', np.array_equal(AB, BA))
print(' AB ≠ BA  →  Matrix multiplication is NOT commutative')

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

AB == BA? False
 AB ≠ BA  →  Matrix multiplication is NOT commutative


In [30]:
# Proof 3: (AB)ᵀ = BᵀAᵀ
AB_T  = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print('(AB)ᵀ =\n', AB_T)
print('\nBᵀAᵀ =\n', BT_AT)
print('\n(AB)ᵀ == BᵀAᵀ?', np.array_equal(AB_T, BT_AT))
print(' Reversal property of transpose proved')

(AB)ᵀ =
 [[23 51]
 [13 29]]

BᵀAᵀ =
 [[23 51]
 [13 29]]

(AB)ᵀ == BᵀAᵀ? True
 Reversal property of transpose proved


System of Linear Equations


  2x − 3y +  z = −1

   x −  y + 2z = −3
   
  3x +  y −  z =  9


In [31]:
#  Solve AX = B using Inverse Method
coeff = np.array([[ 2, -3,  1],
                  [ 1, -1,  2],
                  [ 3,  1, -1]], dtype=float)
constants = np.array([-1, -3, 9], dtype=float)

# Method 1: Manual inverse
X_manual = np.dot(np.linalg.inv(coeff), constants)
print('Method 1 — Manual Inverse (X = A⁻¹ · B):')
print(f'  x = {X_manual[0]:.4f}')
print(f'  y = {X_manual[1]:.4f}')
print(f'  z = {X_manual[2]:.4f}')

# Method 2: np.linalg.inv
X_linalg = np.linalg.inv(coeff).dot(constants)
print('\nMethod 2 — np.linalg.inv:')
print(f'  x = {X_linalg[0]:.4f}')
print(f'  y = {X_linalg[1]:.4f}')
print(f'  z = {X_linalg[2]:.4f}')

# Verification
verified = np.allclose(np.dot(coeff, X_linalg), constants)
print(f'\nVerification — A · X ≈ B: {verified} ')

Method 1 — Manual Inverse (X = A⁻¹ · B):
  x = 2.0000
  y = 1.0000
  z = -2.0000

Method 2 — np.linalg.inv:
  x = 2.0000
  y = 1.0000
  z = -2.0000

Verification — A · X ≈ B: True 


10.2  Experiment — How Fast is NumPy?


This experiment benchmarks plain Python lists against NumPy arrays across four operations on 1,000,000-element data (matrices: 1000×1000). All timings are measured in a single session.

In [32]:
# Setup
SIZE = 1_000_000

py_list1 = list(range(SIZE))
py_list2 = list(range(SIZE))
np_arr1  = np.arange(SIZE, dtype=float)
np_arr2  = np.arange(SIZE, dtype=float)

print(f'Data size: {SIZE:,}')
print('Ready to benchmark.')

Data size: 1,000,000
Ready to benchmark.


In [33]:
# 1. Element-wise Addition
start = time.time()
result_py = [a + b for a, b in zip(py_list1, py_list2)]
time_py = time.time() - start

start = time.time()
result_np = np_arr1 + np_arr2
time_np = time.time() - start

print('Element-wise Addition (size 1,000,000)')
print(f'  Python : {time_py:.6f} s')
print(f'  NumPy  : {time_np:.6f} s')
print(f'  Speedup: {time_py/time_np:.1f}× faster')

Element-wise Addition (size 1,000,000)
  Python : 0.072179 s
  NumPy  : 0.004758 s
  Speedup: 15.2× faster


In [34]:
# 2. Element-wise Multiplication
start = time.time()
result_py = [a * b for a, b in zip(py_list1, py_list2)]
time_py = time.time() - start

start = time.time()
result_np = np_arr1 * np_arr2
time_np = time.time() - start

print('Element-wise Multiplication (size 1,000,000)')
print(f'  Python : {time_py:.6f} s')
print(f'  NumPy  : {time_np:.6f} s')
print(f'  Speedup: {time_py/time_np:.1f}× faster')

Element-wise Multiplication (size 1,000,000)
  Python : 0.163817 s
  NumPy  : 0.005036 s
  Speedup: 32.5× faster


In [35]:
# 3. Dot Product
start = time.time()
dot_py = sum(a * b for a, b in zip(py_list1, py_list2))
time_py = time.time() - start

start = time.time()
dot_np = np.dot(np_arr1, np_arr2)
time_np = time.time() - start

print('Dot Product (size 1,000,000)')
print(f'  Python : {time_py:.6f} s')
print(f'  NumPy  : {time_np:.6f} s')
print(f'  Speedup: {time_py/time_np:.1f}× faster')

Dot Product (size 1,000,000)
  Python : 0.089694 s
  NumPy  : 0.001552 s
  Speedup: 57.8× faster


In [36]:
# 4. Matrix Multiplication
# Python: 100×100 (1000×1000 would take several minutes)
M = 100
mat_py1 = [[random.random() for _ in range(M)] for _ in range(M)]
mat_py2 = [[random.random() for _ in range(M)] for _ in range(M)]

start = time.time()
result_py = [[sum(mat_py1[i][k] * mat_py2[k][j] for k in range(M))
              for j in range(M)] for i in range(M)]
time_py_100 = time.time() - start
estimated_1000 = time_py_100 * 1000   # O(n³) scaling

# NumPy: 1000×1000
mat_np1 = np.random.random((1000, 1000))
mat_np2 = np.random.random((1000, 1000))

start = time.time()
result_np = np.dot(mat_np1, mat_np2)
time_np = time.time() - start

print('Matrix Multiplication')
print(f'  Python (100×100)     : {time_py_100:.4f} s')
print(f'  Python (1000×1000)   : ~{estimated_1000:.0f} s  (estimated via O(n³) scaling)')
print(f'  NumPy  (1000×1000)   : {time_np:.4f} s')
print(f'  Estimated Speedup    : ~{estimated_1000/time_np:.0f}× faster')

Matrix Multiplication
  Python (100×100)     : 0.1116 s
  Python (1000×1000)   : ~112 s  (estimated via O(n³) scaling)
  NumPy  (1000×1000)   : 0.0668 s
  Estimated Speedup    : ~1672× faster


Summary — Why is NumPy Faster?
  
Key Reasons for NumPy's Speed

   Vectorised C-level operations — eliminates Python interpreter loop overhead

   Contiguous memory layout — maximises CPU cache utilisation

   BLAS / LAPACK integration — highly optimised routines for linear algebra

  Multi-threading — matrix operations leverage multiple CPU cores automatically
